name = "Plant Registry and Cookbook Widgets"
author = "Damglador"
version = "1.3" 
description = "Adds 2 buttons in top left corner of the screen.\nYou may need set crafting menu size to 6 or below for better look bcs Im lazy so there is no configs.\nУдачі у вивченні гри! :)"
api_version = 10
priority = 0
---------------------------------------------------

dont_starve_compatible = false
reign_of_giants_compatible = false
shipwrecked_compatible = false
hamlet_compatible = false

dst_compatible = true

---------------------------------------------------

all_clients_require_mod = false
client_only_mod = true

---------------------------------------------------

icon_atlas = "modicon.xml"
icon = "modicon.tex"

---------------------------------------------------

configuration_options = {
    {
        name = "Position",
        label = "Position",
        options = {
            {description = "Top Left (Default)", data = "tl"},
            {description = "Top Right", data = "tr"},
        },
        default = "tl",
    },
    {
		name = "CB_pos_X",
		label = "Cookbook position X",
		options = {
            {description = "0", data = 0},
            {description = "5", data = 5},
            {description = "10", data = 10},
            {description = "15", data = 15},
            {description = "20", data = 20},
            {description = "25", data = 25},
            {description = "30", data = 30},
            {description = "35", data = 35},
            {description = "40 (Default)", data = 40},
            {description = "45", data = 45},
            {description = "50", data = 50},
            {description = "55", data = 55},
            {description = "60", data = 60},
            {description = "65", data = 65},
            {description = "70", data = 70},
            {description = "75", data = 75},
            {description = "80", data = 80},
            {description = "85", data = 85},
            {description = "90", data = 90},
            {description = "95", data = 95},
            {description = "100", data = 100},
            {description = "105", data = 105},
            {description = "110", data = 110},
            {description = "115", data = 115},
            {description = "120", data = 120},
            {description = "125", data = 125},
            {description = "130", data = 130},
            {description = "135", data = 135},
            {description = "140", data = 140},
            {description = "145", data = 145},
            {description = "150", data = 150},
            {description = "155", data = 155},
            {description = "160", data = 160},
            {description = "165", data = 165},
            {description = "170", data = 170},
            {description = "175", data = 175},
            {description = "180", data = 180},
            {description = "185", data = 185},
            {description = "190", data = 190},
            {description = "195", data = 195},
            {description = "200", data = 200},
            {description = "205", data = 205},
            {description = "210", data = 210},
            {description = "215", data = 215},
            {description = "220", data = 220},
            {description = "225", data = 225},
            {description = "230", data = 230},
            {description = "235", data = 235},
            {description = "240", data = 240},
            {description = "245", data = 245},
            {description = "250", data = 250},
            {description = "255", data = 255},
            {description = "260", data = 260},
            {description = "265", data = 265},
            {description = "270", data = 270},
            {description = "275", data = 275},
            {description = "280", data = 280},
            {description = "285", data = 285},
            {description = "290", data = 290},
            {description = "295", data = 295},
            {description = "300", data = 300},
		},
		default = 40,
	},
    {
		name = "CB_pos_Y",
		label = "Cookbook position Y",
		options = {
            {description = "0", data = 0},
            {description = "5", data = 5},
            {description = "10", data = 10},
            {description = "15", data = 15},
            {description = "20", data = 20},
            {description = "25", data = 25},
            {description = "30", data = 30},
            {description = "35", data = 35},
            {description = "40 (Default)", data = 40},
            {description = "45", data = 45},
            {description = "50", data = 50},
            {description = "55", data = 55},
            {description = "60", data = 60},
            {description = "65", data = 65},
            {description = "70", data = 70},
            {description = "75", data = 75},
            {description = "80", data = 80},
            {description = "85", data = 85},
            {description = "90", data = 90},
            {description = "95", data = 95},
            {description = "100", data = 100},
            {description = "105", data = 105},
            {description = "110", data = 110},
            {description = "115", data = 115},
            {description = "120", data = 120},
            {description = "125", data = 125},
            {description = "130", data = 130},
            {description = "135", data = 135},
            {description = "140", data = 140},
            {description = "145", data = 145},
            {description = "150", data = 150},
            {description = "155", data = 155},
            {description = "160", data = 160},
            {description = "165", data = 165},
            {description = "170", data = 170},
            {description = "175", data = 175},
            {description = "180", data = 180},
            {description = "185", data = 185},
            {description = "190", data = 190},
            {description = "195", data = 195},
            {description = "200", data = 200},
            {description = "205", data = 205},
            {description = "210", data = 210},
            {description = "215", data = 215},
            {description = "220", data = 220},
            {description = "225", data = 225},
            {description = "230", data = 230},
            {description = "235", data = 235},
            {description = "240", data = 240},
            {description = "245", data = 245},
            {description = "250", data = 250},
            {description = "255", data = 255},
            {description = "260", data = 260},
            {description = "265", data = 265},
            {description = "270", data = 270},
            {description = "275", data = 275},
            {description = "280", data = 280},
            {description = "285", data = 285},
            {description = "290", data = 290},
            {description = "295", data = 295},
            {description = "300", data = 300},
		},
		default = 40,
	},
    {
		name = "PR_pos_X",
		label = "Plant registry position X",
		options = {
            {description = "0", data = 0},
            {description = "5", data = 5},
            {description = "10", data = 10},
            {description = "15", data = 15},
            {description = "20", data = 20},
            {description = "25", data = 25},
            {description = "30", data = 30},
            {description = "35", data = 35},
            {description = "40 (Default)", data = 40},
            {description = "45", data = 45},
            {description = "50", data = 50},
            {description = "55", data = 55},
            {description = "60", data = 60},
            {description = "65", data = 65},
            {description = "70", data = 70},
            {description = "75", data = 75},
            {description = "80", data = 80},
            {description = "85", data = 85},
            {description = "90", data = 90},
            {description = "95", data = 95},
            {description = "100", data = 100},
            {description = "105", data = 105},
            {description = "110", data = 110},
            {description = "115", data = 115},
            {description = "120", data = 120},
            {description = "125", data = 125},
            {description = "130", data = 130},
            {description = "135", data = 135},
            {description = "140", data = 140},
            {description = "145", data = 145},
            {description = "150", data = 150},
            {description = "155", data = 155},
            {description = "160", data = 160},
            {description = "165", data = 165},
            {description = "170", data = 170},
            {description = "175", data = 175},
            {description = "180", data = 180},
            {description = "185", data = 185},
            {description = "190", data = 190},
            {description = "195", data = 195},
            {description = "200", data = 200},
            {description = "205", data = 205},
            {description = "210", data = 210},
            {description = "215", data = 215},
            {description = "220", data = 220},
            {description = "225", data = 225},
            {description = "230", data = 230},
            {description = "235", data = 235},
            {description = "240", data = 240},
            {description = "245", data = 245},
            {description = "250", data = 250},
            {description = "255", data = 255},
            {description = "260", data = 260},
            {description = "265", data = 265},
            {description = "270", data = 270},
            {description = "275", data = 275},
            {description = "280", data = 280},
            {description = "285", data = 285},
            {description = "290", data = 290},
            {description = "295", data = 295},
            {description = "300", data = 300},
		},
		default = 40,
	},
    {
		name = "PR_pos_Y",
		label = "Plant registry position Y",
		options = {
            {description = "0", data = 0},
            {description = "5", data = 5},
            {description = "10", data = 10},
            {description = "15", data = 15},
            {description = "20", data = 20},
            {description = "25", data = 25},
            {description = "30", data = 30},
            {description = "35", data = 35},
            {description = "40", data = 40},
            {description = "45", data = 45},
            {description = "50", data = 50},
            {description = "55", data = 55},
            {description = "60", data = 60},
            {description = "65", data = 65},
            {description = "70", data = 70},
            {description = "75", data = 75},
            {description = "80", data = 80},
            {description = "85", data = 85},
            {description = "90", data = 90},
            {description = "95", data = 95},
            {description = "100 (Default)", data = 100},
            {description = "105", data = 105},
            {description = "110", data = 110},
            {description = "115", data = 115},
            {description = "120", data = 120},
            {description = "125", data = 125},
            {description = "130", data = 130},
            {description = "135", data = 135},
            {description = "140", data = 140},
            {description = "145", data = 145},
            {description = "150", data = 150},
            {description = "155", data = 155},
            {description = "160", data = 160},
            {description = "165", data = 165},
            {description = "170", data = 170},
            {description = "175", data = 175},
            {description = "180", data = 180},
            {description = "185", data = 185},
            {description = "190", data = 190},
            {description = "195", data = 195},
            {description = "200", data = 200},
            {description = "205", data = 205},
            {description = "210", data = 210},
            {description = "215", data = 215},
            {description = "220", data = 220},
            {description = "225", data = 225},
            {description = "230", data = 230},
            {description = "235", data = 235},
            {description = "240", data = 240},
            {description = "245", data = 245},
            {description = "250", data = 250},
            {description = "255", data = 255},
            {description = "260", data = 260},
            {description = "265", data = 265},
            {description = "270", data = 270},
            {description = "275", data = 275},
            {description = "280", data = 280},
            {description = "285", data = 285},
            {description = "290", data = 290},
            {description = "295", data = 295},
            {description = "300", data = 300},
		},
		default = 100,
	}
}